#!/bin/bash
#
# helper script for RGM backup with Restic
#
# Copyrights 2021 & onwards, SCC France, Eric Belhomme <ebelhomme@fr.scc.com>

source /srv/rgm/backup/environment
$RESTICBIN --repo ${BACKUP_PATH} -p ${RESTICPWDFILE} ${*}