#!/bin/bash
#
# Copyright (C) 2019-2020 RGM Team
# 2019-04-19 - v. 1.0 - Eric Belhomme <ebelhomme@fr.scc.com>
#
# LICENCE :
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
#########################################

if [ $UID -ne 0 ]; then
    echo -e "\e[1;31mError :\e[22m rgmupdate requires root privileges to execute\e[0m"
    exit 1
fi

ANSIBLEPB=0
ANSIBLEGL=0
ANSIBLERN=0
ANSIBLEDV=0
ANSIBLEBK=1
ANSIBLEYM=0
#GITROLES=()
BACKUP_DIR="/srv/rgm/backup"
ANSIBLE_PLB_ARGS=
ANSIBLE_RGM_INSTALLER_REPO="https://github.com/RGM-OSC/ansible-playbook-rgm-installer.git"
ANSIBLE_ROOT="/root/$(basename "$ANSIBLE_RGM_INSTALLER_REPO" | sed 's/\.git//')"
CURDIR=$(pwd -P)


function print_help() {

    echo -e " \e[1m-+- \e[34mRGM\e[39m updater tool -+-\e[0m\n"
    echo -e "Usage:\n\n  \e[1mrgmupdate -h -p -r -u -a -g <role:commit> -o <opts>\e[0m\n"
    echo -e "  -h               : this help message"
    echo -e "  -p               : update Ansible playbook from remote Git repo prior to run the update playbook"
    echo -e "  -r               : update Ansible roles from using Ansible Galaxy prior to run the update playbook"
    echo -e "  -d               : switch to dev (unstable) ansible playbook version"
    echo -e "  -u               : run the Ansible update playbook only"
    echo -e "  -a               : synonym of -p -r -u"
    echo -e "  -b               : disables preliminary SQL backups"
    echo -e "  -y               : proceed to a preliminary \"yum update\" before ansible-playbook execution"
    echo -e "  -o <opts>        : pass extra parameters to ansible-playbook command line"
    echo -e "\n(c) 2019 RGM team - http://www.rgm-cloud.io"
    exit 1
}


while getopts hpruag:o: arg; do
    case "$arg" in
        h) print_help ;;
        p) ANSIBLEPB=1 ;;
        r) ANSIBLEGL=1 ;;
        u) ANSIBLERN=1 ;;
        d) ANSIBLEDV=1 ;;
        b) ANSIBLEBK=0 ;;
        y) ANSIBLEYM=1 ;;
        o) ANSIBLE_PLB_ARGS="$OPTARG" ;;
        a)
            ANSIBLEPB=1
            ANSIBLEGL=1
            ANSIBLERN=1
            ANSIBLEYM=1
            ;;
        *) print_help;;
    esac
done

if [[ $ANSIBLEPB -eq 0 && $ANSIBLEGL -eq 0 && $ANSIBLERN -eq 0 ]]; then
    print_help
fi

if [ $ANSIBLEBK -eq 1 ]; then
    CURDATE=$(date +'%Y-%m-%d-%Hh%M')
    if [ ! -e $BACKUP_DIR || ! -d $BACKUP_DIR ]; then
        mkdir -p $BACKUP_DIR
    fi
    for DB in ged grafana lilac nagiosbp nagvis notifier rgmweb; do
        OUTFILE="${BACKUP_DIR}/rgmupdate_${CURDATE}_${DB}.sql.gz"
        echo "Creating SQL dump for $DB database on $OUTFILE"
        mysqldump --compact --add-drop-table $DB | gzip > $OUTFILE
    done
fi

if [ $ANSIBLEYM -eq 1 ]; then
    yum update -y
fi

if [ ! -e $ANSIBLE_ROOT ]; then
    echo -e "\e[31mAnsible root not found, force -p -r\e[0m\n"
    ANSIBLEPB=1
    ANSIBLEGL=1
    cd $(dirname $ANSIBLE_ROOT)
    git clone $ANSIBLE_RGM_INSTALLER_REPO
fi

if [ $ANSIBLEPB -eq 1 ]; then
    cd $ANSIBLE_ROOT
    git fetch --all
    git reset --hard
    git checkout master
    ANSIBLEGL=1
fi

if [ $ANSIBLEDV -eq 1 ]; then
    cd $ANSIBLE_ROOT
    git fetch --all
    git reset --hard
    git checkout dev
    ANSIBLEGL=1
fi

if [ $ANSIBLEGL -eq 1 ]; then
    cd $ANSIBLE_ROOT
    ansible-galaxy install -f -p ${ANSIBLE_ROOT}/roles -r ${ANSIBLE_ROOT}/roles/requirements.yml
fi

if [ $ANSIBLERN -eq 1 ]; then
    cd $ANSIBLE_ROOT
    ansible-playbook ${ANSIBLE_PLB_ARGS} rgm-installer.yml
fi

cd $CURDIR